/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.pkg7;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author omars
 */
public class QuizFrame extends javax.swing.JFrame {

    private Student s;
    private InstructorManager im;
    private CourseManager cm;
    private StudentManager sm;
    private UserManager um;
    private Course c;
    private Lesson lesson;

    private int currentQuestion = 0;
    private int score = 0;

    /**
     * Creates new form QuizFrame
     */
    public QuizFrame(UserManager um, CourseManager cm, InstructorManager im,
            StudentManager sm, Student s, Course c, Lesson lesson) {

        this.s = s;
        this.im = im;
        this.cm = cm;
        this.sm = sm;
        this.um = um;
        this.c = c;
        this.lesson = lesson;

        initComponents();
        loadQuestion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsGroup = new javax.swing.ButtonGroup();
        questionLabel = new javax.swing.JLabel();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        opt4 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        nextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        questionLabel.setText("Question");

        optionsGroup.add(opt1);
        opt1.setText("a");

        optionsGroup.add(opt2);
        opt2.setText("b");

        optionsGroup.add(opt4);
        opt4.setText("d");

        optionsGroup.add(opt3);
        opt3.setText("c");

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(opt2)
                        .addComponent(opt1)
                        .addComponent(opt3)
                        .addComponent(opt4)))
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextBtn)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt1)
                .addGap(4, 4, 4)
                .addComponent(opt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(nextBtn)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        Quiz q = lesson.getQuiz();
        int correctAnswer = q.getCorrectAnswers().get(currentQuestion);

        int selected = -1;
        if (opt1.isSelected()) {
            selected = 0;
        }
        if (opt2.isSelected()) {
            selected = 1;
        }
        if (opt3.isSelected()) {
            selected = 2;
        }
        if (opt4.isSelected()) {
            selected = 3;
        }

        if (selected == -1) {
            JOptionPane.showMessageDialog(this, "Please select an answer.");
            return;
        }

        if (selected == correctAnswer) {
            score++;
        }

        currentQuestion++;
        loadQuestion();
    }//GEN-LAST:event_nextBtnActionPerformed
    private void loadQuestion() {
        Quiz q = lesson.getQuiz();

        if (currentQuestion >= q.getQuestions().size()) {
            finishQuiz();
            return;
        }

        questionLabel.setText(q.getQuestions().get(currentQuestion));

        ArrayList<String> opts = q.getOptions().get(currentQuestion);

        opt1.setText(opts.get(0));
        opt2.setText(opts.get(1));
        opt3.setText(opts.get(2));
        opt4.setText(opts.get(3));

        optionsGroup.clearSelection();
    }

    private void finishQuiz() {

        s.saveQuizScore(c.getCourseId(), lesson.getLessonId(), score);
        JsonDatabase.saveUsers(sm, im);

        JOptionPane.showMessageDialog(this,
                "Quiz completed! Your score: " + score);

        this.dispose();
        new CourseDisplay(um, cm, im, sm, s, c).setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QuizFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton nextBtn;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    private javax.swing.ButtonGroup optionsGroup;
    private javax.swing.JLabel questionLabel;
    // End of variables declaration//GEN-END:variables
}