package lab.pkg7;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author omars
 */
public class ViewEnrolledStudents extends javax.swing.JFrame {

    /**
     * Creates new form SearchAndUpdate
     */
  

    public ViewEnrolledStudents() {
        initComponents();
        SearchTable.setAutoCreateRowSorter(true);
        DefaultTableModel model = (DefaultTableModel) SearchTable.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(model);
        SearchTable.setRowSorter(sorter);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        searchByNameLabel = new javax.swing.JLabel();
        searchByIDLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchIDtext = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        SearchNameText = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        SearchTable = new javax.swing.JTable();
        SearchButton = new javax.swing.JButton();
        UserId = new javax.swing.JLabel();
        Role = new javax.swing.JLabel();
        NameText = new javax.swing.JScrollPane();
        Name = new javax.swing.JTextArea();
        AgeText = new javax.swing.JScrollPane();
        Age = new javax.swing.JTextArea();
        UpdateButton = new javax.swing.JButton();
        Progress = new javax.swing.JLabel();
        Gpa = new javax.swing.JTextField();
        EnrolledCourses = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Gpa1 = new javax.swing.JTextField();
        Gpa2 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchByNameLabel.setText("Search By Name");

        searchByIDLabel.setText("Search By ID");

        SearchIDtext.setColumns(20);
        SearchIDtext.setRows(5);
        jScrollPane1.setViewportView(SearchIDtext);

        SearchNameText.setColumns(20);
        SearchNameText.setRows(5);
        jScrollPane2.setViewportView(SearchNameText);

        SearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "UserId", "Role", "Username", "Email", "Enrolled Courses", "Progress"
            }
        ));
        jScrollPane4.setViewportView(SearchTable);

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        UserId.setText("UserId");

        Role.setText("Role");

        Name.setColumns(20);
        Name.setRows(5);
        NameText.setViewportView(Name);

        Age.setColumns(20);
        Age.setRows(5);
        AgeText.setViewportView(Age);

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        Progress.setText("Progress");

        Gpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GpaActionPerformed(evt);
            }
        });

        EnrolledCourses.setText("Enrolled Courses");

        Username.setText("Username");

        Gpa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gpa1ActionPerformed(evt);
            }
        });

        Gpa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gpa2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Progress, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Gpa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(UpdateButton)
                                .addComponent(Gpa2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 445, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SearchButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(searchByNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchByIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Role, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UserId, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(NameText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EnrolledCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(Gpa1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 104, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchByIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchByNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchButton)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(UserId, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Role, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gpa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(EnrolledCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(Gpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Gpa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(UpdateButton))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        DefaultTableModel m = (DefaultTableModel) SearchTable.getModel();

        String idText = SearchIDtext.getText() == null ? "" : SearchIDtext.getText().trim();
        String nameText = SearchNameText.getText() == null ? "" : SearchNameText.getText().trim();

        boolean hasId = !idText.isEmpty();
        boolean hasName = !nameText.isEmpty();

        if ((hasId && hasName) || (!hasId && !hasName)) {
            JOptionPane.showMessageDialog(this, "please enter a name or an id not both or neither");
            return;
        }

        m.setRowCount(0);

        if (hasId) {
            int id;
            try {
                id = Integer.parseInt(idText);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Enter a numeric ID");
                return;
            }

            if (!sms.contains(id)) {
                JOptionPane.showMessageDialog(this, "No Student found with this ID");
                return;
            }

            Student s = sms.getRecord(id);
            if (s != null) {
                m.addRow(new Object[]{
                    s.getStudentID(), s.getName(), s.getAge(), s.getGender(), s.getDepartment(), s.getGpa()
                });
            } else {
                JOptionPane.showMessageDialog(this, "No Student found with this ID");
            }

        } else {
            ArrayList<Student> foundStudents = sms.getRecordByName(nameText);

            if (foundStudents == null || foundStudents.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Student found with this name");
                return;
            }

            for (Student z : foundStudents) {
                m.addRow(new Object[]{
                    z.getStudentID(), z.getName(), z.getAge(), z.getGender(), z.getDepartment(), z.getGpa()
                });
            }
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        String name = "", gender = "";
        int age = 0;
        double gpa = 0;
        int selectedRow = SearchTable.getSelectedRow();

        if (Name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Name");
            return;
        } else {
            name = Name.getText();
        }

        if (Age.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an Age");
            return;
        }
        try {
            age = Integer.parseInt(Age.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for Age");
            return;
        }

        if (Male.isSelected()) {
            gender = "Male";
        } else if (Female.isSelected()) {
            gender = "Female";
        } else {
            JOptionPane.showMessageDialog(this, "Please select a gender");
            return;
        }

        String dep = (String) Department.getSelectedItem();

        if (Gpa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a GPA");
            return;
        }
        try {
            gpa = Double.parseDouble(Gpa.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for GPA");
            return;
        }

        if (age < 0) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Age");
            return;
        }

        if (gpa > 4 || gpa < 0) {
            JOptionPane.showMessageDialog(this, "Please enter a GPA between 0 and 4");
            return;
        }

        if (!name.matches("[A-Za-z]+")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Name");
            return;
        }
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a student to delete.");
            return;
        }

        int id = (int) SearchTable.getValueAt(selectedRow, 0);
        String idString = String.valueOf(id);
        Student s = new Student(id, name, age, gender, dep, gpa);
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to update student with ID: " + id + "?",
                "Confirm update",
                javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            sms.update(idString, s);
            javax.swing.JOptionPane.showMessageDialog(this, "Student updated successfully.");

        }
        setVisible(false);
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void GpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GpaActionPerformed

    private void Gpa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gpa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gpa1ActionPerformed

    private void Gpa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gpa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gpa2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    //public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SearchAndUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SearchAndUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SearchAndUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SearchAndUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SearchAndUpdate().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Age;
    private javax.swing.JScrollPane AgeText;
    private javax.swing.JLabel EnrolledCourses;
    private javax.swing.JTextField Gpa;
    private javax.swing.JTextField Gpa1;
    private javax.swing.JTextField Gpa2;
    private javax.swing.JTextArea Name;
    private javax.swing.JScrollPane NameText;
    private javax.swing.JLabel Progress;
    private javax.swing.JLabel Role;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextArea SearchIDtext;
    private javax.swing.JTextArea SearchNameText;
    private javax.swing.JTable SearchTable;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel UserId;
    private javax.swing.JLabel Username;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel searchByIDLabel;
    private javax.swing.JLabel searchByNameLabel;
    // End of variables declaration//GEN-END:variables
}
